# Generated by Django 6.0.3 on 2026-04-12 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacionPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveSmallIntegerField()),
                ('fichas', models.PositiveIntegerField(default=1000)),
                ('estado', models.CharField(choices=[('unido', 'Unido'), ('listo', 'Listo'), ('jugando', 'Jugando'), ('eliminado', 'Eliminado'), ('salio', 'Salio')], default='unido', max_length=20)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('salio_en', models.DateTimeField(blank=True, null=True)),
                ('es_ganador', models.BooleanField(default=False)),
                ('posicion_final', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'participacion en partida',
                'verbose_name_plural': 'participaciones en partida',
                'ordering': ['numero_asiento'],
            },
        ),
        migrations.CreateModel(
            name='PartidaPoker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='esperando', max_length=20)),
                ('maximo_jugadores', models.PositiveSmallIntegerField(default=6)),
                ('ciega_pequena', models.PositiveIntegerField(default=10)),
                ('ciega_grande', models.PositiveIntegerField(default=20)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'partida de poker',
                'verbose_name_plural': 'partidas de poker',
                'ordering': ['-creada_en'],
            },
        ),
    ]
