# Generated by Django 6.0.3 on 2026-04-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participacionpartida',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_en_partidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participacionpartida',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='partidas.partidapoker'),
        ),
        migrations.AddConstraint(
            model_name='participacionpartida',
            constraint=models.UniqueConstraint(fields=('partida', 'numero_asiento'), name='asiento_unico_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='participacionpartida',
            constraint=models.UniqueConstraint(fields=('partida', 'usuario'), name='usuario_unico_por_partida'),
        ),
    ]
