# Generated by Django 6.0.3 on 2026-04-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0003_partidapoker_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManoPoker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mano', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('preflop', 'Preflop'), ('finalizada', 'Finalizada')], default='preparando', max_length=20)),
                ('cartas_comunitarias', models.CharField(blank=True, max_length=50)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manos', to='partidas.partidapoker')),
            ],
            options={
                'verbose_name': 'mano de poker',
                'verbose_name_plural': 'manos de poker',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='CartaPrivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('codigo', models.CharField(max_length=3)),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_privadas', to='partidas.participacionpartida')),
                ('mano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_privadas', to='partidas.manopoker')),
            ],
            options={
                'verbose_name': 'carta privada',
                'verbose_name_plural': 'cartas privadas',
                'ordering': ['orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='manopoker',
            constraint=models.UniqueConstraint(fields=('partida', 'numero_mano'), name='numero_mano_unico_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='cartaprivada',
            constraint=models.UniqueConstraint(fields=('mano', 'participacion', 'orden'), name='carta_privada_unica_por_orden'),
        ),
    ]
