# Generated by Django 6.0.3 on 2026-04-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_manopoker_cartaprivada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manopoker',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manos_ganadas_provisionalmente', to='partidas.participacionpartida'),
        ),
        migrations.AddField(
            model_name='manopoker',
            name='turno_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_actuales', to='partidas.participacionpartida'),
        ),
        migrations.AddField(
            model_name='participacionpartida',
            name='activa_en_mano',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccionMano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pasar', 'Pasar'), ('retirarse', 'Retirarse')], max_length=20)),
                ('orden', models.PositiveIntegerField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('mano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='partidas.manopoker')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_en_manos', to='partidas.participacionpartida')),
            ],
            options={
                'verbose_name': 'accion de mano',
                'verbose_name_plural': 'acciones de mano',
                'ordering': ['orden', 'creada_en'],
                'constraints': [models.UniqueConstraint(fields=('mano', 'orden'), name='orden_unico_accion_por_mano')],
            },
        ),
    ]
