# Generated by Django 6.0.3 on 2026-04-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0005_manopoker_ganador_manopoker_turno_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manopoker',
            name='apuesta_actual_ronda',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manopoker',
            name='bote_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manopoker',
            name='mazo_restante',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participacionpartida',
            name='apuesta_en_ronda',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participacionpartida',
            name='ha_actuado_en_ronda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accionmano',
            name='tipo',
            field=models.CharField(choices=[('pasar', 'Pasar'), ('igualar', 'Igualar'), ('retirarse', 'Retirarse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='manopoker',
            name='estado',
            field=models.CharField(choices=[('preparando', 'Preparando'), ('preflop', 'Preflop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('finalizada', 'Finalizada')], default='preparando', max_length=20),
        ),
    ]
