# Generated by Django 6.0.3 on 2026-04-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0006_manopoker_apuesta_actual_ronda_manopoker_bote_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manopoker',
            name='incremento_minimo_subida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accionmano',
            name='tipo',
            field=models.CharField(choices=[('pasar', 'Pasar'), ('igualar', 'Igualar'), ('subir', 'Subir'), ('retirarse', 'Retirarse')], max_length=20),
        ),
    ]
