# Generated by Django 6.0.3 on 2026-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0007_manopoker_incremento_minimo_subida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manopoker',
            name='descripcion_resultado',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='manopoker',
            name='ganadores',
            field=models.ManyToManyField(blank=True, related_name='manos_ganadas', to='partidas.participacionpartida'),
        ),
    ]
