# Generated by Django 6.0.3 on 2026-05-03 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0008_manopoker_descripcion_resultado_manopoker_ganadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manopoker',
            name='turno_actual_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partidapoker',
            name='codigo_privado',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='partidapoker',
            name='es_privada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='participacionpartida',
            name='fichas',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.CreateModel(
            name='SolicitudPartidaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_partida_publica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud de partida publica',
                'verbose_name_plural': 'solicitudes de partida publica',
                'ordering': ['creada_en'],
            },
        ),
    ]
