# Generated by Django 6.0.3 on 2026-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0009_manopoker_turno_actual_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidapoker',
            name='ciega_grande',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='partidapoker',
            name='ciega_pequena',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
