# Generated by Django 6.0.3 on 2026-05-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_mostrado',
        ),
    ]
