# Generated by Django 6.0.3 on 2026-05-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_nombre_mostrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='saldo_total',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
