# Generated by Django 6.0.3 on 2026-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidas_jugadas', models.PositiveIntegerField(default=0)),
                ('victorias', models.PositiveIntegerField(default=0)),
                ('derrotas', models.PositiveIntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('racha_actual', models.IntegerField(default=0)),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estadisticas de jugador',
                'verbose_name_plural': 'estadisticas de jugadores',
                'ordering': ['-puntos', '-victorias', 'usuario__username'],
            },
        ),
    ]
