# Generated by Django 6.0.3 on 2026-04-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('referencia_partida', models.CharField(blank=True, max_length=64)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento de auditoria',
                'verbose_name_plural': 'eventos de auditoria',
                'ordering': ['-creada_en'],
            },
        ),
    ]
